# -*- coding: utf-8 -*-
"""
Created on Fri Oct 17 11:27:25 2025

@author: jlh7349
"""

"""
This script (generated by ChatGPT) is made for the SBSLab git tutorial.
"""

import pandas as pd
import numpy as np

# --- Generate synthetic data ---
np.random.seed(0)
n = 89
df = pd.DataFrame({
    'observed': np.random.normal(100, 10, n),
    'predicted': np.random.normal(102, 10, n)
})

# --- Define functions for CVRMSE and NMBE ---
def cvrmse(y_true, y_pred):
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
    return 100 * rmse / np.mean(y_true)

def nmbe(y_true, y_pred):
    mbe = np.mean(y_pred - y_true)
    return 100 * mbe / np.mean(y_true)

# --- Calculate metrics ---
CVRMSE = cvrmse(df['observed'], df['predicted'])
NMBE = nmbe(df['observed'], df['predicted'])

# --- Print results ---
print(f"CVRMSE: {CVRMSE:.2f}%")
print(f"NMBE: {NMBE:.2f}%")
